package com.yx.po;

import java.util.Date;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.id
     *
     * @mbg.generated Tue Feb 23 09:57:30 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.name
     *
     * @mbg.generated Tue Feb 23 09:57:30 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.abateTime
     *
     * @mbg.generated Tue Feb 23 09:57:30 CST 2021
     */
    private Date abatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.id
     *
     * @return the value of department.id
     *
     * @mbg.generated Tue Feb 23 09:57:30 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.id
     *
     * @param id the value for department.id
     *
     * @mbg.generated Tue Feb 23 09:57:30 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.name
     *
     * @return the value of department.name
     *
     * @mbg.generated Tue Feb 23 09:57:30 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.name
     *
     * @param name the value for department.name
     *
     * @mbg.generated Tue Feb 23 09:57:30 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.abateTime
     *
     * @return the value of department.abateTime
     *
     * @mbg.generated Tue Feb 23 09:57:30 CST 2021
     */
    public Date getAbatetime() {
        return abatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.abateTime
     *
     * @param abatetime the value for department.abateTime
     *
     * @mbg.generated Tue Feb 23 09:57:30 CST 2021
     */
    public void setAbatetime(Date abatetime) {
        this.abatetime = abatetime;
    }
}